# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7a413132ec1bd9c022f47aed819ce3de"
name = "createCardLink"
application_url = "https://create-card-link.vercel.app"
embedded = true

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://create-card-link.vercel.app/auth/callback" ]
